name: Despliegue continuo  hangman-front (Con acciones de Docker)

on: 
  workflow_dispatch:

jobs:
  buildAndPushImage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Login to Github container registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ actor }}
          password: ${{ secrets.TOKEN_GITHUB }}
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build and push Docker Image
        uses: docker/build-push-action@v7
        with:
          context: ./hangman-front
          push: true
          tags: ghcr.io/lpmoreno/hangman-front:latest
          file: ./hangman-front/Dockerfile